#ifndef HCLCD_CONFIG_H_
#define HCLCD_CONFIG_H_

/* Configure RS,RW,E pins ==> (PIN0 to PIN7) */
#define RS				PIN1
#define RW				PIN2
#define E				PIN3

/* Configure Control port ==> (MDIO_PORTA, MDIO_PORTB, MDIO_PORTC, MDIO_PORTD) */
#define CONTROL_PORT	MDIO_PORTD

/* Configure Data port ==> (MDIO_PORTA, MDIO_PORTB, MDIO_PORTC, MDIO_PORTD) */
#define DATA_PORT		MDIO_PORTD

/* Configure 4bit mode Data port pins ==> (PIN_LSB[PIN0, PIN1, PIN2, PIN3], PIN_MSB[PIN4, PIN5, PIN6, PIN7]) */
#define MODE_4BIT_PINS	PIN_MSB

/* Function set Options 
*  1- FUNCTION_SET_8BITS_2LINES
*  2- FUNCTION_SET_8BITS_1LINES
*  3- FUNCTION_SET_4BITS_2LINES
*  4- FUNCTION_SET_4BITS_1LINES
*/
#define HCLCD_FUNCTION_SET		FUNCTION_SET_4BITS_2LINES

/* Display ON/OFF command Options 
*  1- DISPLAY_ON_CURSOR_ON_BLINKING_ON
*  2- DISPLAY_ON_CURSOR_ON_BLINKING_OFF
*  3- DISPLAY_ON_CURSOR_OFF
*  4- DISPLAY_OFF
*/
#define HCLCD_DISPLAY_ON_OFF	DISPLAY_ON_CURSOR_ON_BLINKING_ON

/* Entry Mode command Options 
*  1- ENTRY_MODE_INCREASE_WITH_SHIFT
*  2- ENTRY_MODE_INCREASE
*  3- ENTRY_MODE_DECREASE_WITH_SHIFT
*  4- ENTRY_MODE_DECREASE
*/
#define HCLCD_ENTRY_MODE		ENTRY_MODE_INCREASE

#endif /* HCLCD_CONFIG_H_ */
