#ifndef MEXTI_CONFIG_H_
#define MEXTI_CONFIG_H_

/* Sense Control for EXTI0 Options:
 * 1- MEXTI_LOW_LEVEL
 * 2- MEXTI_ANY_LOGICAL_CHANGE
 * 3- MEXTI_FALLING_EDGE
 * 4- MEXTI_RISING_EDGE
 */
#define MEXTI0_SET_SENSE_CONTROL		MEXTI_LOW_LEVEL

/* Sense Control for EXTI1 Options:
 * 1- MEXTI_LOW_LEVEL
 * 2- MEXTI_ANY_LOGICAL_CHANGE
 * 3- MEXTI_FALLING_EDGE
 * 4- MEXTI_RISING_EDGE
 */
#define MEXTI1_SET_SENSE_CONTROL		MEXTI_ANY_LOGICAL_CHANGE
#endif /* MEXTI_CONFIG_H_ */
