/*
 * MTIMER1_Config.h
 *
 *  Created on: Sep 4, 2023
 *      Author: galal
 */

#ifndef MTIMER1_CONFIG_H_
#define MTIMER1_CONFIG_H_


/* TIMER1 Pre-scaler options:
 * 1- TIMER1_STOP
 * 2- TIMER1_SCALER_1
 * 3- TIMER1_SCALER_8
 * 4- TIMER1_SCALER_64
 * 5- TIMER1_SCALER_256
 * 6- TIMER1_SCALER_1024
 * 7- TIMER1_EXTERNAL_FALLING
 * 8- TIMER1_EXTERNAL_RISING
 * */
#define TIMER1_SET_PRESCALER			TIMER1_SCALER_8

/* TIMER1 Mode Options:
 * 1- TIMER1_NORMAL_MODE
 * 2- TIMER1_PWM_PHASE_CORRECT_8_bit
 * 3- TIMER1_PWM_PHASE_CORRECT_9_bit
 * 4- TIMER1_PWM_PHASE_CORRECT_10_bit
 * 5- TIMER1_CTC_OCR1A
 * 6- TIMER1_FAST_PWM_8_bit
 * 7- TIMER1_FAST_PWM_9_bit
 * 8- TIMER1_FAST_PWM_10_bit
 * 9- TIMER1_PWM_PHASE_AND_FREQUENCY_CORRECT_ICR1
 * 10- TIMER1_PWM_PHASE_AND_FREQUENCY_CORRECT_OCR1A
 * 11- TIMER1_PWM_PHASE_CORRECT_ICR1
 * 12- TIMER1_PWM_PHASE_CORRECT_OCR1A
 * 13- TIMER1_CTC_ICR1
 * 14- TIMER1_FAST_PWM_ICR1
 * 15- TIMER1_FAST_PWM_OCR1A
 * */
#define TIMER1_SET_MODE									TIMER1_NORMAL_MODE


/* OPTIONS FOR OUTPUT COMPARE PIN (OC1A) BEHAVIOUR IN CASE OF NON-PWM MODE:
 * 1- TIMER1_OC1A_DISCONNECTED
 * 2- TIMER1_TOGGLE_OC1A
 * 3- TIMER1_CLEAR_OC1A_NON_INVERTING
 * 4- TIMER1_SET_OC1A_INVERTING
 */
#define TIMER1_OC1A_NON_PWM				  				TIMER1_TOGGLE_OC1A

/*  OPTIONS FOR OUTPUT COMPARE PIN (OC1B) BEHAVIOUR IN CASE OF NON-PWM MODE:
 * 1- TIMER1_OC1B_DISCONNECTED
 * 2- TIMER1_TOGGLE_OC1B
 * 3- TIMER1_CLEAR_OC1B_NON_INVERTING
 * 4- TIMER1_SET_OC1B_INVERTING
 */
#define TIMER1_OC1B_NON_PWM			  					TIMER1_CLEAR_OC1B_NON_INVERTING

/**********************************************************************************************/
/* OPTIONS FOR OUTPUT COMPARE PIN (OC1A) BEHAVIOUR IN CASE OF FAST PWM MODE:
 * TOGGLE_OC1A (FAST_PWM_OCR1A mode should be chosen. Otherwise, OC1A will be disconnected
 * 1- TIMER1_OC1A_DISCONNECTED
 * 2- TIMER1_TOGGLE_OC1A
 * 3- TIMER1_CLEAR_OC1A_NON_INVERTING
 * 4- TIMER1_SET_OC1A_INVERTING
 */
#define TIMER1_OC1A_FAST_PWM							TIMER1_CLEAR_OC1A_NON_INVERTING

/*  OPTIONS FOR OUTPUT COMPARE PIN (OC1B) BEHAVIOUR IN CASE OF FAST PWM MODE:
 * 1- TIMER1_OC1B_DISCONNECTED
 * 2- TIMER1_CLEAR_OC1B_NON_INVERTING
 * 3- TIMER1_SET_OC1B_INVERTING
 * */
#define TIMER1_OC1B_FAST_PWM			  				TIMER1_SET_OC1B_INVERTING

/*****************************************************************************/
/* OPTIONS FOR COMPARE PIN (OC1A) in case of PHASE CORRECT and PHASE & FREQUENCY PWM MODES:
 * TIMER1_TOGGLE_OC1A (PHASE_AND_FREQUENCY_CORRECT_OCR1A or FAST_PWM_ICR1 mode should  be chosen.
 * Otherwise, OC1A will be disconnected
 * 1- TIMER1_OC1A_DISCONNECTED
 * 2- TIMER1_TOGGLE_OC1A
 * 3- TIMER1_CLEAR_OC1A_NON_INVERTING
 * 4- TIMER1_SET_OC1A_INVERTING
 * */
#define TIMER1_OC1A_PHASE								TIMER1_TOGGLE_OC1A

/* OPTIONS FOR COMPARE PIN (OC1B) IN CASE OF PHASE CORRECT and PHASE & FREQUENCY PWM MODES:
 * 1- TIMER1_OC1B_DISCONNECTED
 * 2- TIMER1_CLEAR_OC1B_NON_INVERTING
 * 3- TIMER1_SET_OC1B_INVERTING
 * */
#define TIMER1_OC1B_PHASE								TIMER1_CLEAR_OC1B_NON_INVERTING

/* OPTIONS FOR COMPARE register:
 * 1- CMP_1A
 * 2- CMP_1B
 * */
#define TIMER1_COMPARE_REGISTER							CMP_1A

/* Timer1 TOPValue options:
 * 1- SET_ON_ICR1
 * 2- SET_ON_OCR1A
 */
#define TIMER1_SET_TOP_VALUE 							SET_ON_ICR1

#define TIMER1_ISR_VECTORS								4

/* Options:
 * 1- ENABLE
 * 2- DISABLE
 *  */
#define TIMER1_ICU										ENABLE

/* Options:
 * 1- ENABLE
 * 2- DISABLE
 *  */
#define ICU_NoiseCanceler								DISABLE

/* Edge select options:
 * 1- ICU_RISING_EDGE
 * 2- ICU_FALLING_EDGE
 * */
#define ICU_Edge_Select									ICU_RISING_EDGE

#endif /* MTIMER1_CONFIG_H_ */
